var items = {
  'armor': [
  'Havaiian shirt',
  'Hawaiian shirt of toughness',
  'leather jacket',
  'leather jacket of hardness',
  'leather armor',
  'leather armor of might',
  'orcish ring mail',
  'orcish ring mail of stone skin',
  'studded leather armor',
  'studded leather armor of tenacity',
  'ring mail',
  'ring mail of power',
  'scale mail',
  'scale mail of resistance',
  'orcish chain mail',
  'orcish chain mail of hard-to-hitness',
  'chain mail',
  'chain mail of extra armorness',
  'elven mithril-coat',
  'elven mithril-coat of extreme toughness',
  'splint mail',
  'splint mail of stone handedness',
  'banded mail',
  'banded mail of stone footedness',
  'dwarvish mithril-coat',
  'dwarvish mithril-coat of unbreakability',
  'bronze plate mail',
  'bronze plate mail of tough skin',
  'plate mail',
  'plate mail of tough handedness',
  'crystal plate mail',
  'crystal plate mail of tough footedness',
  'dragon scales',
  'dragon scales of mighty power',
  'dragon scale mail',
  'dragon scale mail of mighty toughness',
  'mummy wrapping',
  'mummy wrapping of great might',
  'orcish cloak',
  'orcish cloak of extra power',
  'dwarvish cloak',
  'dwarvish cloak of extra might',
  'leather cloak',
  'leather cloak of great power',
  'cloak',
  'cloak of displacement',
  'oilskin cloak',
  'oilskin cloak of mirror selves',
  'alchemy smock',
  'alchemy smock of hard hearing',
  'cloak of invisibility',
  'cloak of leaping',
  'cloak of magic resistance',
  'elven cloak',
  'elven cloak of dodging',
  'robe',
  'robe of many things',
  'cloak of protection',
  'fedora',
  'fedora of grognardness',
  'dunce cap',
  'dunce cap of gooniness',
  'dented pot',
  'elven leather helm',
  'helmet',
  'orcish helm',
  'helm of brilliance',
  'helm of opposite alignment',
  'helm of telepathy',
  'dwarvish iron helm',
  'leather gloves',
  'gauntlets',
  'gauntlets of dexterity',
  'gauntlets of fumbling',
  'gauntlets of power',
  'shield',
  'shield of resistance',
  'small shield',
  'small shield of force',
  'orcish shield',
  'orcish shield of foul odor',
  'Uruk-hai shield',
  'elven shield',
  'elven shield of reflection',
  'dwarvish roundshield',
  'dwarvish roundshield of tough beardedness',
  'large shield',
  'large shield of kiting',
  'shield of reflection',
  'low boots',
  'elven boots',
  'kicking boots',
  'fumble boots',
  'levitation boots',
  'jumping boots',
  'speed boots',
  'water walking boots',
  'high boots',
  'iron shoes',
  'tin foil hat',
],'heavy_weapon': [
  'axe',
  'battle axe',
  'pick axe',
  'dwarvish mattock',
  'broadsword',
  'runesword',
  'elvish broadswoard',
  'long sword',
  'katana',
  'two-handed sword',
  'scimitar',
  'silver saber',
  'club',
  'morning star',
  'flail',
  'grappling hook',
  'war hammer',
  'partisan',
  'fauchard',
  'glaive',
  'bec-de-corbin',
  'spetum',
  'lucern hammer',
  'guisarme',
  'ranseur',
  'voulge',
  'bill-guisarme',
  'bardiche',
  'halberd',
  'lance',
],
'light_weapon': [
  'orcish dagger',
  'dagger',
  'silver dagger',
  'elven dagger',
  'worm tooth',
  'knife',
  'stiletto',
  'scalpel',
  'crysknife',
  'orcish short sword',
  'short sword',
  'dwarvish short sword',
  'elven short sword',
  'mace',
  'quarterstaff',
  'orcish spear',
  'spear',
  'silver spear',
  'elven spear',
  'dwarvish spear',
  'javelin',
  'trident',
  'orcish bow',
  'bow',
  'elven bow',
  'yumi',
  'sling',
  'crossbow',
  'dart',
  'shuriken',
  'boomerang',
  'bullwhip',
  'rubber hose',
  'unicorn horn',
],
'wand': [
  'wand',
  'glass wand',
  'oak wand',
  'copper wand',
  'aluminum wand',
  'short wand',
  'spiked wand',
  'balsa wand',
  'ebony wand',
  'silver wand',
  'uranium wand',
  'runed wand',
  'jeweled wand',
  'crystal wand',
  'marble wand',
  'platinum wand',
  'iron wand',
  'long wand',
  'maple wand',
  'tin wand',
  'iridium wand',
  'steel wand',
  'curved wand',
  'pine wand',
  'brass wand',
  'zinc wand',
  'hexagonal wand',
  'forked wand',
  'staff',
  'glass staff',
  'oak staff',
],
'jewelry': [
  'amulet',
  'circular amulet',
  'triangular amulet',
  'concave amulet',
  'spherical amulet',
  'pyramidal amulet',
  'hexagonal amulet',
  'oval amulet',
  'square amulet',
  'octagonal amulet',
  'diamond amulet',
  'ruby amulet',
  'opal amulet',
  'citrine stone amulet',
  'turqoise stone amulet',
  'aquamarine stone amulet',
  'amber stone amulet',
  'yellow glass amulet',
  'black glass amulet',
  'ring',
  'meat ring',
  'gem',
  'dilithium crystal',
  'diamond ring',
  'ruby ring',
  'jacinth stone ring',
  'sapphire ring',
  'black opal ring',
  'emerald ring',
  'turquise stone ring',
  'citrine stone ring',
  'aquamarine stone ring',
  'amber stone ring',
  'topaz stone ring',
  'jet stone ring',
  'opal ring',
  'chrysoberyl stone ring',
  'garnet stone ring',
  'amethyst stone ring',
  'jasper stone ring',
  'fluorite stone ring',
  'jade stone ring',
  'obsidian stone ring',
  'agate stone ring',
  'white glass ring',
  'blue glass ring',
  'red glass ring',
  'yellowish brown glass ring',
  'orange glass ring',
  'yellow glass ring',
  'black glass ring',
  'green glass ring',
  'violet glass ring',
  'luchstone ring',
  'lodestone ring',
  'touchstone ring',
  'flint stone ring',
  'rock ring',
]
};
