var monstersList = [
'orc _ fire _ blade _ storm _ night _ lightnight _ fire _ rainbow',
"black _ dragonette",
"blue _ dragonette",
"green _ dragonette",
"red _ dragonette",
"white _ dragonette",
"metallic _ dragonette",
"brass _ dragonette",
"bronze _ dragonette",
"copper _ dragonette",
"gold _ dragonette",
"silver _ dragonette",
'ornery _ orc',
'hungry _ hobgoblin',
'cave _ dweller',
'great _ beholder',
'rust _ monster',
'grid _ bug',
'giant _ rat',
'gilded _ demon',
'wheeled _ demon',
'radioactive _ serpent',
'spineless _ fiend',
'horned _ cat',
'flying _ blob',
'hopping _ killer',
'flailing _ lizard',
'one- eyed _ troll',
'stinking _ worm',
'boiling _ demon',
'oozing _ beetle',
'mind _ moth',
'brain _ slurper',
'phantom _ ogre',
'library _ goblin',
'acidic _ vole',
'troglodytic _ eagle',
'festering _ cow',
'heavily- armed _ moron',
'slinking _ shadow',
'moon _ crow',
'giant _ ant',
'killer _ bee',
'soldier _ ant',
'fire _ ant',
'giant _ beetle',
'queen _ bee',
'acid _ blob',
'quivering _ blob',
'gelatinous _ cube',
'little _ dog',
'large _ dog',
'wolf _ cub',
'hell _ hound',
'gas _ spore',
'floating _ eye',
'freezing _ sphere',
'flaming _ sphere',
'shocking _ sphere',
'large _ cat',
'winged _ gargoyle',
'dwarf _ lord',
'dwarf _ king',
'mind _ flayer',
'blue _ jelly',
'spotted _ jelly',
'ochre _ jelly',
'large _ kobold',
'kobold _ lord',
'kobold _ shaman',
'small _ mimic',
'large _ mimic',
'giant _ mimic',
'wood _ nymph',
'water _ nymph',
'mountain _ nymph',
'hill _ orc',
'mordor _ orc',
'orc _ shaman',
'rock _ piercer',
'iron _ piercer',
'glass _ piercer',
'sewer _ rat',
'giant _ rat',
'rabid _ rat',
'rock _ mole',
'cave _ spider',
'giant _ spider',
'white _ unicorn',
'gray _ unicorn',
'black _ unicorn',
'fog _ cloud',
'dust _ vortex',
'ice _ vortex',
'energy _ vortex',
'steam _ vortex',
'fire _ vortex',
'long _ worm',
'purple _ worm',
'yellow _ light',
'black _ light',
'giant _ bat',
'vampire _ bat',
'plains _ centaur',
'forest _ centaur',
'mountain _ centaur',
'air _ elemental',
'fire _ elemental',
'earth _ elemental',
'water _ elemental',
'brown _ mold',
'yellow _ mold',
'green _ mold',
'red _ mold',
'violet _ fungus',
'stone _ giant',
'hill _ giant',
'fire _ giant',
'storm _ giant',
'master _ lich',
'giant _ mummy',
'red _ naga',
'black _ naga',
'golden _ naga',
'guardian _ naga',
'gray _ ooze',
'brown _ pudding',
'black _ pudding',
'green _ slime',
'quantum _ mechanic',
'rust _ monster',
'garter _ snake',
'water _ moccasin',
'pit _ viper',
'ice _ troll',
'rock _ troll',
'water _ troll',
'umber _ hulk',
'barrow _ wight',
'carnivorous _ aper',
'giant _ zombie',
'straw _ golem',
'paper _ golem',
'rope _ golem',
'gold _ golem',
'leather _ golem',
'wood _ golem',
'flesh _ golem',
'clay _ golem',
'stone _ golem',
'glass _ golem',
'iron _ golem',
'water _ demon',
'horned _ devil',
'barbed _ devil',
'bone _ devil',
'ice _ devil',
'pit _ fiend',
'mail _ daemon',
'giant _ eel',
'electric _ eel',
'swamp _ crocodile',
"aboleth",
"aboleth _ mage",
"achaierai",
"allip",
"angel",
"astral _ deva",
"planetar",
"solar",
"animated _ object",
"ankheg",
"aranea",
"archon",
"lantern _ archon",
"hound _ archon",
"hound _ archon _ hero",
"trumpet _ archon",
"arrow hawk",
"assassin _ vine",
"athach",
"avoral",
"azer",
"barghest",
"basilisk",
"abyssal _ basilisk",
"behir",
"belker",
"blink _ dog",
"bodak",
"bralani",
"bug bear",
"bulette",
"celestial _ creature",
"centaur",
"chaos _ beast",
"chimera",
"choker",
"chuul",
"cloaker",
"cockatrice",
"couatl",
"dark mantle",
"delver",
"demon",
"babau",
"balor",
"bebilith",
"dretch",
"glabrezu",
"hezrou",
"marilith",
"nalfeshnee",
"quasit",
"retriever",
"succubus",
"vrock",
"derro",
"destrachan",
"devil",
"barbed _ devil",
"bearded _ devil",
"bone _ devil",
"chain _ devil",
"erinyes",
"hellcat",
"horned _ devil",
"ice _ devil",
"imp",
"lemure",
"pit _ fiend",
"devourer",
"digester",
"dinosaur",
"deinonychus",
"elasmosaurus",
"megaraptor",
"triceratops",
"tyrannosaurus",
"dire _ animal",
"dire _ ape",
"dire _ badger",
"dire _ bat",
"dire _ bear",
"dire _ boar",
"dire _ lion",
"dire _ rat",
"dire _ shark",
"dire _ tiger",
"dire _ weasel",
"dire _ wolf",
"dire _ wolverine",
"doppel ganger",
"dragonne",
"drider",
"dryad",
"dwarf",
"deep _ dwarf",
"duergar",
"mountain _ dwarf",
"giant _ eagle",
"elemental",
"air _ elemental",
"earth _ elemental",
"fire _ elemental",
"water _ elemental",
"elf",
"half- elf",
"aquatic _ elf",
"drow",
"gray _ elf",
"wild _ elf",
"wood _ elf",
"ethereal _ filcher",
"ethereal _ marauder",
"ettercap",
"ettin",
"fiendish _ creature",
"formian",
"worker",
"warrior",
"task master",
"myrmarch",
"queen",
"frost _ worm",
"fungus",
"shrieker",
"violet _ fungus",
"gargoyle",
"kapoacinth",
"genie",
"djinni",
"noble _ djinn",
"efreeti",
"janni",
"ghaele",
"ghost",
"ghoul",
"lacedon",
"ghast",
"giant",
"cloud _ giant",
"fire _ giant",
"frost _ giant",
"frost _ giant _ jarl",
"hill _ giant",
"stone _ giant",
"stone _ giant _ elders",
"storm _ giant",
"gibbering _ mouther",
"girallon",
"gnoll",
"gnome",
"svirfneblin",
"forest _ gnome",
"goblin",
"golem",
"clay _ golem",
"flesh _ golem",
"iron _ golem",
"stone _ golem",
"gorgon",
"gray _ render",
"grick",
"griffon",
"grimlock",
"hag",
"annis",
"green _ hag",
"sea _ hag",
"half- celestial",
"half- dragon",
"half- fiend",
"halfling",
"tall fellow",
"deep _ halfling",
"harpy",
"harpy _ archer",
"hell _ hound",
"nessian _ warhound",
"hippogriff",
"hobgoblin",
"homunculus",
"howler",
"hydra",
"pyro hydra",
"cryo hydra",
"inevitable",
"kolyarut",
"marut",
"zelekhut",
"invisible _ stalker",
"kobold",
"kraken",
"krenshar",
"lamia",
"lammasu",
"golden _ protector",
"leonal",
"lich",
"lillend",
"lizard folk",
"locathah",
"lycanthrope",
"were bear",
"were boar",
"dire _ were boar",
"were rat",
"were tiger",
"were wolf",
"were wolf _ lord",
"magmin",
"manticore",
"medusa",
"mephit",
"air _ mephit",
"dust _ mephit",
"earth _ mephit",
"fire _ mephit",
"ice _ mephit",
"magma _ mephit",
"ooze _ mephit",
"salt _ mephit",
"steam _ mephit",
"water _ mephit",
"merfolk",
"mimic",
"minotaur",
"mohrg",
"mummy",
"mummy _ lord",
"naga",
"dark _ naga",
"guardian _ naga",
"spirit _ naga",
"water _ naga",
"night _ hag",
"nightmare",
"cauchemar",
"night shade",
"night crawler",
"night walker",
"night wing",
"nymph",
"ogre",
"ogre _ barbarian",
"merrow",
"ogre _ mage",
"ooze",
"black _ pudding",
"elder _ black _ pudding",
"gelatinous _ cube",
"gray _ ooze",
"ochre _ jelly",
"orc",
"half- orcs",
"otyugh",
"giant _ owl",
"owlbear",
"pegasus",
"phantom _ fungus",
"phase _ spider",
"phasm",
"plane touched",
"aasimar",
"tiefling",
"pseudodragon",
"purple _ worm",
"rakshasa",
"rast",
"ravid",
"razor _ boar",
"remorhaz",
"roc",
"roper",
"rust _ monster",
"sahuagin",
"sahuagin _ mutants",
"malenti",
"salamander",
"satyr",
"scorpionfolk",
"sea _ cat",
"shadow",
"shadow _ mastiff",
"shambling _ mound",
"shield _ guardian",
"shocker _ lizard",
"skeleton",
"skum",
"spectre",
"sphinx",
"andro sphinx",
"crio sphinx",
"gyno sphinx",
"hieraco sphinx",
"spider _ eater",
"sprite",
"grig",
"nixie",
"pixie",
"stirge",
"swarm",
"bat _ swarm",
"centipede _ swarm",
"hellwasp _ swarm",
"locust _ swarm",
"rat _ swarm",
"spider _ swarm",
"tarrasque",
"tendriculos",
"thoqqua",
"titan",
"tojanida",
"treant",
"triton",
"troglodyte",
"troll",
"scrag",
"troll _ hunter",
"unicorn",
"celestial _ charger",
"vampire",
"vampire _ spawn",
"vargouille",
"wight",
"will-o’- wisp",
"winter _ wolf",
"worg",
"wraith",
"dread _ wraith",
"wyvern",
"xill",
"xorn",
"yeth _ hound",
"yrthak",
"zombie",
"ape",
"baboon",
"badger",
"bat",
"black _ bear",
"brown _ bear",
"polar _ bear",
"bison",
"boar",
"camel",
"cat",
"cheetah",
"crocodile",
"giant _ crocodile",
"dog",
"riding _ dog",
"donkey",
"eagle",
"elephant",
"hawk",
"horse",
"heavy _ horse",
"light _ horse",
"heavy _ warhorse",
"light _ warhorse",
"hyena",
"leopard",
"lion",
"lizard",
"monitor _ lizard",
"manta _ ray",
"monkey",
"mule",
"octopus",
"giant _ octopus",
"owl",
"pony",
"war _ pony",
"porpoise",
"rat",
"raven",
"rhinoceros",
"shark",
"snake",
"constrictor _ snake",
"viper _ snake",
"squid",
"giant _ squid",
"tiger",
"toad",
"weasel",
"whale",
"baleen _ whale",
"cachalot _ whale",
"orca",
"wolf",
"wolverine",
"giant _ ant",
"giant _ bee",
"giant _ bombardier _ beetle",
"giant _ fire _ beetle",
"giant _ stag _ beetle",
"giant _ praying _ mantis",
"giant _ wasp",
"monstrous _ centipede",
"monstrous _ scorpion",
"monstrous _ spider"
];
