var fighterNamesList = [
'oth ok',
'targ morn',
'the on del',
'be orth',
'cromm',
'ric chop',
'fled mak',
'wen drud',
'hil da fre ya',
'swith se',
'se hun',
'ce ol hil da',
'den',
'od dryt',
'an frid',
'an vorch op an vor',
'glor drud thang',
'thok kah',
'mand wa ru',
'nath va ra',
"steel ' red here",
"be o - kah",
"del drud krum",
"axe ' wulf",
"grim fre a ferth",
"be orth con thuk",
"ke le steel ceo",
"stan cuth cen",
"thuk re ya be orn ror",
"frid ' ty",
"drud care thun",
"thok ' the od",
"thak werd",
"va ra wenk ro bur",
"hes narg nath",
"wen - ead",
"le of u ' narg",
"thang se",
"le of ae chop",
"se - le of",
"gar ne ' ferth",
"hall ' se",
"ax car or car eax",
"mak kah gar cen",
"wig - dryt",
"nir warc en an",
"ntor war u fi",
"steel - gar mand",
"hrun sirg rand ax",
"sir ' war ur id",
"cath or le of u",
"he re ' war",
"werd - wine eal",
"cuth be orth red cyn",
"steel krom hun werd",
"ror ' dryt tor",
"on ug rand ' frey",
"thok ro read grund",
];
var thiefNamesList = [
"by mund _ hand",
"li af re _ sack ville",
"hil di dad _ burrows",
"gil wise _ whit",
"tin ro _ brandy",
"wil mas _ green",
"grim re _ roper",
"bran dan _ foot",
"pop bin _ good",
"lore _ ville",
"bella ro _ ward",
"or sere _ gardner",
"min pe _ miller",
"gor fi _ sack",
"ica doc _ butcher",
"wil co _ foot",
"com ene _ long",
"hen daddy _ weed",
"re dodo _ took",
"mond man _ green",
"hob va _ gardner",
"mond bella _ maggot",
"tol pos _ bairn",
"gor hil _ feet",
"mar balbo _ leaf",
"pon li _ ville",
"doc ti _ sack",
"blan myr _ took",
"grin mos _ cotton",
"ry la _ hand",
"di har _ gammidge",
"loc son _ long",
"fus bel _ boffin",
"beric fus _ rumble",
"man fer _ boffin",
"grim wise _ baggins",
"de lia _ girdle",
"har dad al _ roper",
"red bal bo _ bitter",
"pip pin _ took",
"sam wise _ hair foot",
"me bell _ horn - ville",
"bell das _ girdle green",
"roge _ cotton - field",
"isum cot _ blower - weed",
"nel gil _ man field",
"pos vin _ ward two",
"fre fast _ burrows green",
"mar malo _ sandy girdle",
"grim blan _ pipe - girdle",
"and ca _ ville rumble",
"brash en _ butcher gardner",
"dro gose _ gamwich foot",
"go ric _ foot - long",
"gomu la _ sack bairn",
"vin bras _ miller - bairn",
"ba mer _ gardner - bolger",
"se lard _ gamgee - hard",
"me py _ buck gam wich",
"da gol _ man - blower",
"be han _ maggot sack ville",
"ever ro _ bairn baggins",
"pob ras _ bottom - sack",
"dod rida _ maggot - brandy",
"angel kar _ sack girdle",
"ped rida _ green - miller",
"vin mac _ hay miller",
"bo di _ rumble - man",
"brand flam _ bolger - maggot",
"go fara _ hand - hard",
"per go _ hard sack",
"chome _ proud - bairn",
"gil ham _ ward - sackville",
"co go _ leaf sack",
"pin cho _ maggot - gamwich",
"tol dad _ miller holm",
"cho be _ small buck",
"du bow _ holm field",
"po rosa _ foot shire",
"dash il di _ long marish",
"bras gis _ bairn field",
];
var wizardNamesList = [
"lil ya",
"rah",
"a ha",
"hak ha",
"tas ' da",
"der qi",
"lu far",
"ri az mad ja",
"sim ma",
"bas",
"la fai",
"a hir",
"i ran",
"ham sur",
"ha ra",
"rid qa",
"had la",
"kan ya",
"ha ra",
"yar ay",
"mi - yas",
"ra ' sul",
"ra feez ya",
"fer yah yid",
"nay dya tu",
"fa ga",
"abd mil",
"as - nya",
"ah on a",
"had kha reef",
"hat ' ti",
"mu ' ha",
"ghu shim",
"ya ' mad",
"ikh a man",
"qai wud",
"lib il",
"abd di ser ga",
"nu - ra",
"zia - mus",
"hai ih min sim",
"fai oya abd za",
"nas a ab ak",
"gan am id sha tha",
"da hiz rak",
"hi - ha ' id",
"rus ai med ' a ha",
"al ay ka",
"med kha man",
"naf at i ha",
"raj ar am am ni",
"sir li o ha",
"wa zai ' fad ya",
"la - sa abd",
"am la riq far",
"dya gu - dat",
"ja - ma ak ha",
"zal ah ra ra",
"sha ab ' lah",
"war za ak af aiz",
"da ' su din",
"mid kia wa",
"mal hus fad mis",
"ram ara aba",
"iz jayn ' mas mi",
"atia abd sah",
"lah - af ah",
"za dran li had ur",
"mal gar a ha",
"mat wah hil il",
"qaj ab a sim",
"na - na biy",
"mot ama - tul",
"meh dat u ma",
"sir ' him sim",
"ha - mid",
"la ly u hu sha",
"i ' ra sa",
"il ra fi sa",
"za wa ka ra",
"ra lah ba ka",
"ki - hi sha a",
"jab - qi ni ya",
"biy sin rah",
"mid mo fi ha",
"uz raa ba di",
"am ' mi sa",
"min - him khay",
"sem hat mi mar",
"ma war i az sa",
"nas ' ha naz",
"qi fir - shed",
"bri - ki ziy",
"jib shid mu leh",
"lub ' kha",
"ha ha ma ma",
"bi mam sa",
"ti ra ni mad",
"hos mur mou zih na",
"dul ha ba al",
];
