var res = {
  tristram_ui_tmx: "media/maps/tristram_ui.tmx",
  tristram_map1_tmx: "media/maps/tristram_map1.tmx",
  tristram_map2_tmx: "media/maps/tristram_map2.tmx",
  roguelikeChar_png: "media/maps/roguelikeChar_transparent.png",
  roguelikeChar_x2_png: "media/maps/roguelikeChar_transparent_x2.png",
  roguelikeDungeon_png: "media/maps/roguelikeDungeon_transparent.png",
  roguelikeIndoor_png: "media/maps/roguelikeIndoor_transparent.png",
  roguelikeSheet_png: "media/maps/roguelikeSheet_transparent.png",
  tints_png: "media/maps/tints.png",
  meta_png: "media/maps/meta.png",
  diablo_heavy_ttf: "media/fonts/diablo-heavy.ttf",
  dialog_png: "media/img/dialog.png",
  anironc_ttf: "media/fonts/anironc.ttf",
  startBackground_png: "media/img/HunterImage.png",
  music_vindsvept_ogg: "media/sound/music_vindsvept.ogg",
  music_heroimmortal_ogg: "media/sound/music_heroimmortal.ogg",
  music_holdtheline_ogg: "media/sound/music_holdtheline.ogg",
  music_airship_ogg: "media/sound/music_airship.ogg",
  music_ajourneyawaits_ogg: "media/sound/music_ajourneyawaits.ogg",
  sound_handleCoins_ogg: "media/sound/sound_handleCoins.ogg",
  sound_handleCoins2_ogg: "media/sound/sound_handleCoins2.ogg",
  sound_wilhelm_ogg: "media/sound/sound_wilhelm.ogg",
  sound_knifeSlice2_ogg: "media/sound/sound_knifeSlice2.ogg"
};

var g_resources = [
  {type: "tmx", src: res.tristram_ui_tmx},
  {type: "tmx", src: res.tristram_map1_tmx},
  {type: "tmx", src: res.tristram_map2_tmx},
  {type: "png", src: res.roguelikeChar_png},
  {type: "png", src: res.roguelikeDungeon_png},
  {type: "png", src: res.roguelikeIndoor_png},
  {type: "png", src: res.roguelikeSheet_png},
  {type: "png", src: res.dialog_png},
  res.diablo_heavy_ttf,
  res.anironc_ttf,
  {type: "png", src: res.startBackground_png},
  {type: "ogg", src: res.music_holdtheline_ogg},
  {type: "ogg", src: res.music_ajourneyawaits_ogg},
  {type: "ogg", src: res.music_heroimmortal_ogg},
  {type: "ogg", src: res.music_vindsvept_ogg},
  {type: "ogg", src: res.sound_handleCoins_ogg},
  {type: "ogg", src: res.sound_handleCoins2_ogg},
  {type: "ogg", src: res.sound_wilhelm_ogg},
  {type: "ogg", src: res.sound_knifeSlice2_ogg}
];
