var heroScripts = [
];
/*
var shopkeeperScripts = [
    "I sense a soul in search of answers...",
    "Hello, my friend. Stay awhile and listen...",
    "Can't a fella drink in peace?",
    "Good day! How may I serve you?",
    "Well, what can I do for ya?",
    "Greetings, good master.",
    "What ails you, my friend?",
    "Pssst... over here...",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Good morning, champion.",
    "Good morning, my friend.",
    "Good morning, hero.",
    "Greetings.",
    "Greetings, champion.",
    "Greetings, my friend.",
    "Greetings, hero.",
    "Hello.",
    "Hello, champion.",
    "Hello, my friend.",
    "Hello, hero.",
    "I have a quest for you.",
    "I have a reward for you!",
    "I have news for you.",
    "I need your help.",
    "Need some help?",
    "Stay a while and listen.",
    "You have returned!",
    "Let's deal, my friend.",
    "What'cha need?",
    "Welcome avenger.",
    "Your presence honors me.",
    "Allow me to advise you.",
    "Approach and let's trade.",
    "Steel is strong, but magic stronger.",
    "There's nothing the right potion can't cure.",
    "Welcome to my shop.",
    "Hail to you, champion.",
    "Yes, warrior?",
    "Quickly, traveler.",
    "Return, anytime.",
    "Tell me your troubles.",
    "Hey there.",
    "What do you need?",
    "What do you want?",
    ];
    */
var shopkeeperScripts = [
    "I sense a soul in search of answers...",
    "Hello, my friend. Stay awhile and listen...",
    "Can't a fella drink in peace?",
    "Good day! How may I serve you?",
    "Well, what can I do for ya?",
    "Greetings, good master. Welcome to the Tavern of the Rising Sun!",
    "What ails you, my friend?",
    "Pssst... over here...",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Greetings.",
    "Hello.",
    "The Order welcomes you.",
    "Welcome back, my friend. We are still clearing the monastery, but you're welcome to stay here as long as you need.",
    "Yes?",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Good to see you.",
    "Greetings.",
    "Hello.",
    "I need your help.",
    "Oh, hi there. It's good to see you again. Hey, nice armor!",
    "What can I do for you?",
    "What'cha need?",
    "Yes?",
    "Good afternoon.",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Good to see you!",
    "Greetings.",
    "Hello.",
    "I have a quest for you.",
    "I have a reward for you!",
    "I have news for you.",
    "Stay a while and listen.",
    "Yes?",
    "You have returned!",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Good to see you again. Since the Rogues have been moving back into their monastery, they haven't been buying anything from me!",
    "Greetings.",
    "Hello.",
    "Let's deal, my friend.",
    "May I help you?",
    "I need your help.",
    "What'cha need?",
    "Yes?",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Greetings.",
    "Hello.",
    "Hello again, outlander. Word of your great exploits in the east has reached us, even here.",
    "I need your help.",
    "The Sisterhood welcomes you.",
    "Welcome avenger.",
    "Yes?",
    "As you command!",
    "Done.",
    "Immediately.",
    "Yes!",
    "Good day.",
    "Good evening.",
    "Good luck.",
    "Good morning.",
    "Greetings.",
    "Greetings, my friend.",
    "Hello.",
    "Hot enough for you.",
    "I need your help.",
    "Your presence honors me.",
    "Welcome back my friend. Remember, if you need to return to the West, I'll be glad to escort you with my caravan.",
    "Where can I take you?",
    "Where can I take you today?",
    "Yes?",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Greetings.",
    "Greetings, hero.",
    "Hello.",
    "Hello again. Things have been very quiet around here since you left.",
    "I need you help.",
    "Return, anytime.",
    "Tell me your troubles.",
    "There's no trouble a mug can't cure.",
    "Yes?",
    "Good afternoon.",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Good to see you!",
    "Greetings.",
    "Hello.",
    "I have a quest for you.",
    "I have a reward for you!",
    "I have news for you.",
    "Stay a while and listen.",
    "Yes?",
    "You have returned!",
    "Allow me to advise you.",
    "Approach and let's trade.",
    "Ask and learn.",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Greetings.",
    "Hello.",
    "I need your help.",
    "Steel is strong, but magic stronger.",
    "Take care.",
    "Welcome back, stranger. I hope the battle goes well in the east.",
    "Yes?",
    "Come again.",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Greetings.",
    "Hello.",
    "Hi, there.",
    "How do you like desert life?",
    "Look what crawled out of the desert.",
    "I need your help.",
    "Welcome to the Desert Rain.",
    "What'cha need?",
    "What's your pleasure?",
    "Yes?",
    "Blessings to you.",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Greetings.",
    "Hello.",
    "How may I help you?",
    "I need your help.",
    "It is my honor to serve you.",
    "Thank all that's Holy, you're still alive. I can see in your eyes that glorious Kurast has been despoiled by evil. I don't think I can bear to hear about it. I wish you luck.",
    "What can I do for you?",
    "Yes?",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Greetings.",
    "Hello.",
    "Heyyyy.",
    "Hey there.",
    "Heyyy, don't take any wooden gold pieces.",
    "Hi.",
    "Huh?",
    "Hey, I need your help.",
    "Hey, you buyin'?",
    "Let me buy you a drink.",
    "So you've been to Kurast, huh? Did you happen to bring back any Skatsimi ale-potions?",
    "Water, huh. Never touch the stuff.",
    "Yeah?",
    "Yes?",
    "Be careful out there.",
    "Come back this way, have you? What, didn't you see enough action here the first time?",
    "Fare thee well.",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Greetings.",
    "Hail, hero.",
    "Hello.",
    "I need your help.",
    "Need some help?",
    "Who goes there?",
    "Yes?",
    "Yes, citizen?",
    "Ahh... Greetings, good hero. Please, make yourself at home in my city.",
    "Ahh... Our hero returns.",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Greetings.",
    "Hello.",
    "I grant you audience.",
    "I need your help.",
    "Please state your business.",
    "Welcome, hero.",
    "Yes?",
    "Back again, uh?",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Greetings.",
    "Hello.",
    "Huh? Did you say something?",
    "I need your help.",
    "Okay, be that way.",
    "There's nothing the right potion can't cure.",
    "Welcome to my shop.",
    "Well, what the hell do you want? Oh, it's you. Uh, hi there.",
    "Yes?",
    "You'll be back.",
    "Ahoy, mate.",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Good sailing.",
    "Good to see you.",
    "Good to see you again.",
    "Greetings.",
    "Hail to you, champion.",
    "Hello.",
    "Hello again. Let me know when you've had enough of this place. I'll gladly sail away from here.",
    "I need your help.",
    "My ship is your ship.",
    "Thank you.",
    "Welcome avenger",
    "What can I do for you?",
    "What do you need?",
    "Yes?",
    "You'd best be about your business here, I want to leave as soon as you're ready.",
    "You should be thankful that I don't charge you for ferrying you across the sea.",
    "Good day.",
    "Good evening.",
    "Good luck.",
    "Good morning.",
    "Greetings.",
    "Greetings, my friend.",
    "Hello.",
    "Hot enough for you.",
    "I need your help.",
    "Your presence honors me.",
    "Welcome back my friend. Remember, if you need to return to the West, I'll be glad to escort you with my caravan.",
    "Where can I take you?",
    "Where can I take you today?",
    "Yes?",
    "For the last time, stop pestering... Oh, it's you. Welcome! Welcome!",
    "Go away!",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Good to see you.",
    "Good to see you again.",
    "Greetings.",
    "Hail to you, champion.",
    "Hello.",
    "I need your help.",
    "Thank you.",
    "Welcome, avenger.",
    "What?",
    "What can I do for you?",
    "What do you need?",
    "What do you want?",
    "Yes?",
    "Your presence honors me.",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Good to see you.",
    "Greetings.",
    "Hail to you, champion.",
    "Hello.",
    "I'm surprised you made it back all in one piece. Most mortals who come back from Hell are usually dead... or undead as it turns out.",
    "Thank you.",
    "Welcome, avenger.",
    "What can I do for you?",
    "What do you need?",
    "Yes?",
    "Your presence honors me.",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Greetings.",
    "Hail to you, champion.",
    "Hello.",
    "Thank you.",
    "Truth be told, I didn't expect to see you again. Did you happen to see any magical weapons in Hell?",
    "Welcome, avenger.",
    "Yes?",
    "Godspeed.",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Good to see you.",
    "Good to see you again.",
    "Greetings.",
    "Hail to you, champion.",
    "Hello.",
    "I need your help.",
    "Thank you.",
    "Welcome, avenger.",
    "What can I do for you?",
    "What do you need?",
    "Yes?",
    "Your presence honors me.",
    "Back so soon? Don't be ashamed. Even Ormus knows that the fires of Hell would wilt any man resolve.",
    "Good day.",
    "Good evening.",
    "Good morning.",
    "Good to see you.",
    "Good to see you again.",
    "Greetings.",
    "Hail to you, champion.",
    "Hello.",
    "I need your help.",
    "Thank you.",
    "Welcome, avenger.",
    "What can I do for you?",
    "What do you need?",
    "Yes?",
    "Your presence honors me.",
    "Good to see you again.",
    "Hail to you, champion.",
    "Hello.",
    "Of course.",
    "Thank you.",
    "Welcome, avenger.",
    "What do you need?",
    "Yes?",
    "Your presence honors me.",
    "Good to see you.",
    "Good to see you again.",
    "Greetings.",
    "Hail to you, champion.",
    "Hello.",
    "Thank you.",
    "Welcome, avenger.",
    "What can I do for you?",
    "What do you need?",
    "Yes?",
    "Can I help you?",
    "Good evening.",
    "Good morning.",
    "Good morning, warrior.",
    "Hello.",
    "Hello, warrior.",
    "What are your needs?",
    "Yes?",
    "Afternoon.",
    "At your service.",
    "Can I help you?",
    "Evening.",
    "Good day.",
    "Good to see you again.",
    "Morning.",
    "What do you need?",
    "Yeah?",
    "You're back.",
    "Good afternoon.",
    "Good evening.",
    "Greetings hero.",
    "Hello.",
    "How may I be of help?",
    "Salutations.",
    "The morning comes.",
    "Your presence is welcome.",
    "Be quick about it!",
    "Hmm?",
    "Surprised to see you.",
    "What!",
    "What is it?",
    "Yes?",
    "Afternoon.",
    "Can I help you?",
    "Evening.",
    "Morning.",
    "Quickly, traveler.",
    "What is it?",
    "Yes?",
    "Yes, warrior?",
];
