var wizardSpellList = [
'orc _ fire _ blade _ storm _ night _ lightnight _ fire _ rainbow',
'force _ bolt',
'drain _ life',
'magic _ missile',
'cone _ of _ cold',
'fireball',
'finger _ of _ death',
'protection',
'turn _ undead',
'create _ monster',
'remove _ curse',
'create _ familiar',
'detect _ monster',
'light',
'detect _ food',
'clairvoyance',
'detect _ unseen',
'identity',
'detect _ treasure',
'magic _ mapping',
'sleep',
'confuse _ monster',
'slow _ monster',
'cause _ fear',
'charm _ monster',
'jumping',
'haste _ self',
'invisibility',
'levitation',
'teleport _ away',
'knock',
'wizard _ lock',
'dig',
'polymorph',
'cancellation',
'amplify _ damage',
'dim _ vision',
'weaken',
'iron _ maiden',
'terror',
'confuse',
'life _ tap',
'attract',
'decrepify',
'lower _ resist',
'teeth',
'bone _ armor',
'poison _ dagger',
'corpse _ explosion',
'bone _ wall',
'poison _ explosion',
'bone _ spear',
'bone _ prison',
'poison _ nova',
'bone _ spirit',
'raise _ skeleton',
'skeleton _ mastery',
'clay _ golem',
'golem _ mastery',
'raise _ skeletal _ mage',
'blood _ golem',
'summon _ resist',
'iron _ golem',
'fire _ golem',
'revive',
'ice _ bolt',
'frozen _ armor',
'frost _ nova',
'ice _ blast',
'shiver _ armor',
'glacial _ spike',
'blizzard',
'chilling _ armor',
'frozen _ orb',
'cold _ mastery',
'fire _ bolt',
'warmth',
'inferno',
'blaze',
'fireball',
'fire _ wall',
'enchant',
'meteor',
'fire _ mastery',
'hydra',
'charged _ bolt',
'telekinesis',
'static _ field',
'lightning',
'nova',
'chain _ lightning',
'teleport',
'thunder _ storm',
'energy _ shield',
'lightning _ mastery',
'firestorm',
'molten _ boulder',
'arctic _ blast',
'fissure',
'cyclone _ armor',
'twister',
'volcano',
'tornado',
'hurricane',
'armageddon',
'werewolf',
'lycanthropy',
'werebear',
'maul',
'feral _ rage',
'fire _ claws',
'rabies',
'shock _ wave',
'hunger',
'fury',
'raven',
'poison _ creeper',
'oak _ sage',
'summon _ spirit _ wolf',
'carrion _ vine',
'heart _ of _ wolverine',
'summon _ dire _ wolf',
'solar _ creeper',
'spirit _ of _ barbs',
'summon _ grizzly',
"acid _ arrow",
"acid _ fog",
"acid _ splash",
"aid",
"air _ walk",
"alarm",
"align _ weapon",
"alter _ self",
"analyze _ dweomer",
"animal _ growth",
"animal _ messenger",
"animal _ shapes",
"animal _ trance",
"animate _ dead",
"animate _ objects",
"animate _ plants",
"animate _ rope",
"antilife _ shell",
"antimagic _ field",
"antipathy",
"antiplant _ shell",
"arcane _ eye",
"arcane _ lock",
"arcane _ mark",
"arcane _ sight",
"greater _ arcane _ sight",
"astral _ projection",
"atonement",
"augury",
"awaken",
"baleful _ polymorph",
"bane",
"banishment",
"barkskin",
"bear’s _ endurance",
"mass _ bear’s _ endurance",
"bestow _ curse",
"binding",
"black _ tentacles",
"blade _ barrier",
"blasphemy",
"bless",
"bless _ water",
"bless _ weapon",
"blight",
"blindness",
"deafness",
"blink",
"blur",
"break _ enchantment",
"bull’s _ strength",
"mass _ bull’s _ strength",
"burning _ hands",
"call _ lightning",
"call _ lightning _ storm",
"calm _ animals",
"calm _ emotions",
"cat’s _ grace",
"mass _ cat’s _ grace",
"cause _ fear",
"chain _ lightning",
"changestaff",
"chaos _ hammer",
"charm _ animal",
"charm _ monster",
"mass _ charm _ monster",
"charm _ person",
"chill _ metal",
"chill _ touch",
"circle _ of _ death",
"clairaudience",
"clairvoyance",
"clenched _ fist",
"cloak _ of _ chaos",
"clone",
"cloudkill",
"color _ spray",
"command",
"greater _ command",
"command _ plants",
"command _ undead",
"commune",
"commune _ with _ nature",
"comprehend _ languages",
"cone _ of _ cold",
"confusion",
"lesser _ confusion",
"consecrate",
"contact _ other _ plane",
"contagion",
"contingency",
"continual _ flame",
"control _ plants",
"control _ undead",
"control _ water",
"control _ weather",
"control _ winds",
"create _ food _ and _ water",
"create _ greater _ undead",
"create _ undead",
"create _ water",
"creeping _ doom",
"crushing _ despair",
"crushing _ hand",
"cure _ critical _ wounds",
"mass _ cure _ critical _ wounds",
"cure _ light _ wounds",
"mass _ cure _ light _ wounds",
"cure _ minor _ wounds",
"cure _ moderate _ wounds",
"mass _ cure _ moderate _ wounds",
"cure _ serious _ wounds",
"mass _ cure _ serious _ wounds",
"curse _ water",
"dancing _ lights",
"darkness",
"darkvision",
"daylight",
"daze",
"daze _ monster",
"death _ knell",
"death _ ward",
"deathwatch",
"deep _ slumber",
"deeper _ darkness",
"delay _ poison",
"delayed _ blast _ fireball",
"demand",
"desecrate",
"destruction",
"detect _ animals _ or _ plants",
"detect _ chaos",
"detect _ evil",
"detect _ good",
"detect _ law",
"detect _ magic",
"detect _ poison",
"detect _ scrying",
"detect _ secret _ doors",
"detect _ snares _ and _ pits",
"detect _ thoughts",
"detect _ undead",
"dictum",
"dimension _ door",
"dimensional _ anchor",
"dimensional _ lock",
"diminish _ plants",
"discern _ lies",
"discern _ location",
"disguise _ self",
"disintegrate",
"dismissal",
"dispel _ chaos",
"dispel _ evil",
"dispel _ good",
"dispel _ law",
"dispel _ magic",
"greater _ dispel _ magic",
"displacement",
"disrupt _ undead",
"disrupting _ weapon",
"divination",
"divine _ favor",
"divine _ power",
"dominate _ animal",
"dominate _ monster",
"dominate _ person",
"doom",
"dream",
"eagle’s _ splendor",
"mass _ eagle’s _ splendor",
"earthquake",
"elemental _ swarm",
"endure _ elements",
"energy _ drain",
"enervation",
"enlarge _ person",
"mass _ enlarge _ person",
"entangle",
"enthrall",
"entropic _ shield",
"erase",
"ethereal _ jaunt",
"etherealness",
"expeditious _ retreat",
"explosive _ runes",
"eyebite",
"fabricate",
"faerie _ fire",
"false _ life",
"false _ vision",
"fear",
"feather _ fall",
"feeblemind",
"find _ the _ path",
"find _ traps",
"finger _ of _ death",
"fire _ seeds",
"fire _ shield",
"fire _ storm",
"fire _ trap",
"fireball",
"flame _ arrow",
"flame _ blade",
"flame _ strike",
"flaming _ sphere",
"flare",
"flesh _ to _ stone",
"fly",
"floating _ disk",
"fog _ cloud",
"forbiddance",
"forcecage",
"forceful _ hand",
"foresight",
"fox’s _ cunning",
"mass _ fox’s _ cunning",
"freedom",
"freedom _ of _ movement",
"freezing _ sphere",
"gaseous _ form",
"gate",
"geas",
"quest",
"lesser _ geas",
"gentle _ repose",
"ghost _ sound",
"ghoul _ touch",
"giant _ vermin",
"glibness",
"glitterdust",
"globe _ of _ invulnerability",
"lesser _ globe _ of _ invulnerability",
"glyph _ of _ warding",
"greater _ glyph _ of _ warding",
"goodberry",
"good _ hope",
"grasping _ hand",
"grease",
"guards _ and _ wards",
"guidance",
"gust _ of _ wind",
"hallow",
"hallucinatory _ terrain",
"halt _ undead",
"harm",
"haste",
"heal",
"mass _ heal",
"heal _ mount",
"heat _ metal",
"helping _ hand",
"heroes’ _ feast",
"heroism",
"greater _ heroism",
"hide _ from _ animals",
"hide _ from _ undead",
"hideous _ laughter",
"hold _ animal",
"hold _ monster",
"mass _ hold _ monster",
"hold _ person",
"mass _ hold _ person",
"hold _ portal",
"holy _ aura",
"holy _ smite",
"holy _ sword",
"holy _ word",
"horrid _ wilting",
"hypnotic _ pattern",
"hypnotism",
"ice _ storm",
"identify",
"illusory _ script",
"illusory _ wall",
"imbue _ with _ spell _ ability",
"implosion",
"imprisonment",
"incendiary _ cloud",
"inflict _ critical _ wounds",
"mass _ inflict _ critical _ wounds",
"inflict _ light _ wounds",
"mass _ inflict _ light _ wounds",
"inflict _ minor _ wounds",
"inflict _ moderate _ wounds",
"mass _ inflict _ moderate _ wounds",
"inflict _ serious _ wounds",
"mass _ inflict _ serious _ wounds",
"insanity",
"insect _ plague",
"instant _ summons",
"interposing _ hand",
"invisibility",
"greater _ invisibility",
"mass _ invisibility",
"invisibility _ purge",
"invisibility _ sphere",
"iron _ body",
"ironwood",
"irresistible _ dance",
"jump",
"keen _ edge",
"knock",
"know _ direction",
"legend _ lore",
"lesser _ (spell _ name)",
"levitate",
"light",
"lightning _ bolt",
"limited _ wish",
"liveoak",
"locate _ creature",
"locate _ object",
"longstrider",
"lullaby",
"mage _ armor",
"mage _ hand",
"mage’s _ disjunction",
"mage’s _ faithful _ hound",
"mage’s _ lucubration",
"mage’s _ magnificent _ mansion",
"mage’s _ private _ sanctum",
"mage’s _ sword",
"magic _ aura",
"magic _ circle _ against _ chaos",
"magic _ circle _ against _ evil",
"magic _ circle _ against _ good",
"magic _ circle _ against _ law",
"magic _ fang",
"greater _ magic _ fang",
"magic _ jar",
"magic _ missile",
"magic _ mouth",
"magic _ stone",
"magic _ vestment",
"magic _ weapon",
"greater _ magic _ weapon",
"major _ creation",
"major _ image",
"make _ whole",
"mark _ of _ justice",
"mass _ (spell _ name)",
"maze",
"meld _ into _ stone",
"mending",
"message",
"meteor _ swarm",
"mind _ blank",
"mind _ fog",
"minor _ creation",
"minor _ image",
"miracle",
"mirage _ arcana",
"mirror _ image",
"misdirection",
"mislead",
"mnemonic _ enhancer",
"modify _ memory",
"moment _ of _ prescience",
"mount",
"move _ earth",
"neutralize _ poison",
"nightmare",
"nondetection",
"obscure _ object",
"obscuring _ mist",
"open",
"close",
"order’s _ wrath",
"overland _ flight",
"owl’s _ wisdom",
"mass _ owl’s _ wisdom",
"passwall",
"pass _ without _ trace",
"permanency",
"permanent _ image",
"persistent _ image",
"phantasmal _ killer",
"phantom _ steed",
"phantom _ trap",
"phase _ door",
"planar _ ally",
"greater _ planar _ ally",
"lesser _ planar _ ally",
"planar _ binding",
"greater _ planar _ binding",
"lesser _ planar _ binding",
"plane _ shift",
"plant _ growth",
"poison",
"polar _ ray",
"polymorph",
"polymorph _ any _ object",
"power _ word _ blind",
"power _ word _ kill",
"power _ word _ stun",
"prayer",
"prestidigitation",
"prismatic _ sphere",
"prismatic _ spray",
"prismatic _ wall",
"produce _ flame",
"programmed _ image",
"project _ image",
"protection _ from _ arrows",
"protection _ from _ chaos",
"protection _ from _ energy",
"protection _ from _ evil",
"protection _ from _ good",
"protection _ from _ law",
"protection _ from _ spells",
"prying _ eyes",
"greater _ prying _ eyes",
"purify _ food _ and _ drink",
"pyrotechnics",
"quench",
"rage",
"rainbow _ pattern",
"raise _ dead",
"ray _ of _ enfeeblement",
"ray _ of _ exhaustion",
"ray _ of _ frost",
"read _ magic",
"reduce _ animal",
"reduce _ person",
"mass _ reduce _ person",
"refuge",
"regenerate",
"reincarnate",
"remove _ blindness",
"remove _ deafness",
"remove _ curse",
"remove _ disease",
"remove _ fear",
"remove _ paralysis",
"repel _ metal _ or _ stone",
"repel _ vermin",
"repel _ wood",
"repulsion",
"resilient _ sphere",
"resistance",
"resist _ energy",
"restoration",
"greater _ restoration",
"lesser _ restoration",
"resurrection",
"reverse _ gravity",
"righteous _ might",
"rope _ trick",
"rusting _ grasp",
"sanctuary",
"scare",
"scintillating _ pattern",
"scorching _ ray",
"screen",
"scrying",
"greater _ scrying",
"sculpt _ sound",
"searing _ light",
"secret _ chest",
"secret _ page",
"secure _ shelter",
"see _ invisibility",
"seeming",
"sending",
"sepia _ snake _ sigil",
"sequester",
"shades",
"shadow _ conjuration",
"greater _ shadow _ conjuration",
"shadow _ evocation",
"greater _ shadow _ evocation",
"shadow _ walk",
"shambler",
"shapechange",
"shatter",
"shield",
"shield _ of _ faith",
"shield _ of _ law",
"shield _ other",
"shillelagh",
"shocking _ grasp",
"shout",
"greater _ shout",
"shrink _ item",
"silence",
"silent _ image",
"simulacrum",
"slay _ living",
"sleep",
"sleet _ storm",
"slow",
"snare",
"soften _ earth _ and _ stone",
"solid _ fog",
"song _ of _ discord",
"soul _ bind",
"sound _ burst",
"speak _ with _ animals",
"speak _ with _ dead",
"speak _ with _ plants",
"spectral _ hand",
"spell _ immunity",
"greater _ spell _ immunity",
"spell _ resistance",
"spellstaff",
"spell _ turning",
"spider _ climb",
"spike _ growth",
"spike _ stones",
"spiritual _ weapon",
"statue",
"status",
"stinking _ cloud",
"stone _ shape",
"stoneskin",
"stone _ tell",
"stone _ to _ flesh",
"storm _ of _ vengeance",
"suggestion",
"mass _ suggestion",
"summon _ instrument",
"summon _ monster",
"summon _ nature’s _ ally",
"summon _ swarm",
"sunbeam",
"sunburst",
"symbol _ of _ death",
"symbol _ of _ fear",
"symbol _ of _ insanity",
"symbol _ of _ pain",
"symbol _ of _ persuasion",
"symbol _ of _ sleep",
"symbol _ of _ stunning",
"symbol _ of _ weakness",
"sympathetic _ vibration",
"sympathy",
"telekinesis",
"telekinetic _ sphere",
"telepathic _ bond",
"teleport",
"teleport _ object",
"greater _ teleport",
"teleportation _ circle",
"temporal _ stasis",
"time _ stop",
"tiny _ hut",
"tongues",
"touch _ of _ fatigue",
"touch _ of _ idiocy",
"transformation",
"transmute _ metal _ to _ wood",
"transmute _ mud _ to _ rock",
"transmute _ rock _ to _ mud",
"transport _ via _ plants",
"trap _ the _ soul",
"tree _ shape",
"tree _ stride",
"true _ resurrection",
"true _ seeing",
"true _ strike",
"undeath _ to _ death",
"undetectable _ alignment",
"unhallow",
"unholy _ aura",
"unholy _ blight",
"unseen _ servant",
"vampiric _ touch",
"veil",
"ventriloquism",
"virtue",
"vision",
"wail _ of _ the _ banshee",
"wall _ of _ fire",
"wall _ of _ force",
"wall _ of _ ice",
"wall _ of _ iron",
"wall _ of _ stone",
"wall _ of _ thorns",
"warp _ wood",
"water _ breathing",
"water _ walk",
"waves _ of _ exhaustion",
"waves _ of _ fatigue",
"web",
"weird",
"whirlwind",
"whispering _ wind",
"wind _ walk",
"wind _ wall",
"wish",
"wood _ shape",
"word _ of _ chaos",
"word _ of _ recall",
"zone _ of _ silence",
"zone _ of _ truth",
];
var thiefSpellList = [
'orc _ fire _ blade _ storm _ night _ lightnight _ fire _ rainbow',
'backstab',
'magic _ arrow',
'fire _ arrow',
'cold _ arrow',
'multiple _ shot',
'exploding _ arrow',
'ice _ arrow',
'guided _ arrow',
'strafe',
'immolation _ arrow',
'freezing _ arrow',
'critical _ strike',
'penetrate',
'valkyrie',
'pierce',
'jab',
'power _ strike',
'poison _ javelin',
'impale',
'lightning _ bolt',
'charged _ strike',
'plague _ javelin',
'fend',
'lightning _ strike',
'lightning _ fury',
'tiger _ strike',
'dragon _ talon',
'dragon _ claw',
'fists _ of _ fire',
'cobra _ strike',
'dragon _ tail',
'claws _ of _ thunder',
'blades _ of _ ice',
'dragon _ flight',
'phoenix _ strike',
'claw _ mastery',
'psychic _ hammer',
'burst _ of _ speed',
'cloak _ of _ shadows',
'weapon _ block',
'fade',
'shadow _ warrior',
'mind _ blast',
'venom',
'shadow _ master',
'fire _ blast',
'shock _ web',
'blade _ sentinel',
'charged _ bolt _ sentry',
'wake _ of _ fire',
'blade _ fury',
'lightning _ sentry',
'wake _ of _ inferno',
'death _ sentry',
'blade _ shield',
];
var fighterSpellList = [
'orc _ fire _ blade _ storm _ night _ lightnight _ fire _ rainbow',
'bash',
'leap',
'double _ swing',
'stun',
'double _ throw',
'leap _ attack',
'concentrate',
'frenzy',
'whirlwind',
'berserk',
'howl',
'find _ potion',
'taunt',
'shout',
'battle _ cry',
'battle _ orders',
'grim _ ward',
'war _ cry',
'battle _ command',
'sacrifice',
'smite',
'holy _ bolt',
'zeal',
'charge',
'vengeance',
'blessed _ hammer',
'conversion',
'holy _ shield',
'fist _ of _ the _ heavens',
'prayer',
'resist _ fire',
'resist _ cold',
'resist _ lightning',
'defiance',
'cleansing',
'vigor',
'meditation',
'redemption',
'salvation',
'might',
'holy _ fire',
'thorns',
'blessed _ aim',
'concentration',
'holy _ freeze',
'holy _ shock',
'sanctuary',
'fanaticism',
'conviction',
];
